accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('registration/', views.register, name='registration'),
]

blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('team/', views.TeamView.as_view(), name='team'),
    path('downloads/', views.DownloadsView.as_view(), name='downloads'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('contributors/', views.ContribView.as_view(), name='contributors'),
    path('blog/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('blog/post/', views.post, name='post')
]

studentsinresistance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

blog/models.py
from django.conf import settings
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone


def get_image_filename(instance, filename):
    title = instance.Post.title
    slug = slugify(title)
    return "images/%s-%s" % (slug, filename)

class Post(models.Model):
    """Blog post model"""
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # TODO: Change to user model when user app implemented
    issue = models.ManyToManyField('Issue', related_name='post_issue')
    category = models.ManyToManyField('Category', related_name='post_category')
    title = models.CharField(max_length=200)
    body = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class PostImage(models.Model):
    """Blog post images"""
    post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_image_filename, verbose_name="Image")

class Category(models.Model):
    """Post categories"""
    name = models.CharField(max_length=20)

class Issue(models.Model):
    """Table for zine issue"""
    issue_number = models.IntegerField(default=-1)
    title = models.CharField(max_length=200)
    description = models.TextField()
    published_date = models.DateTimeField(blank=True, null=True)
    link = models.URLField()

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.issue_number)

accounts/forms.py
from django import forms
from accounts.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta():
        model = User
        fields = ('username', 'password', 'email')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

blog/forms.py
from django import forms

from blog.models import Post, PostImage, Issue, Category

class PostForm(forms.ModelForm):
    title = forms.CharField(max_length=200, label = 'Title')
    body = forms.Textarea()
    issue = forms.ModelChoiceField(queryset=Issue.objects.all(), to_field_name='issue_number')
    category = forms.ModelChoiceField(queryset=Category.objects.all(), to_field_name='name')

    class Meta:
        model = Post
        fields = ('title', 'body', 'issue', 'category', )

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)

class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    
    class Meta:
        model = PostImage
        fields = ('image', )

accounts/views.py
from django.shortcuts import render
from django.views import generic
from accounts.forms import UserForm, UserProfileInfoForm

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'registration/registration.html',
                   {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})

blog/views.py
from django.contrib import messages
from django.forms import modelformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from blog.models import Post, PostImage
from blog.forms import PostForm, ImageForm


class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_posts'

    def get_queryset(self):
	    '''Return last five blog posts'''
	    return Post.objects.order_by('-published_date')[:5]

class DetailView(generic.DetailView):
	model = Post
	template_name = 'blog/detail.html'

class AboutView(generic.TemplateView):
	template_name = 'blog/about.html'

class TeamView(generic.TemplateView):
	template_name = 'blog/team.html'

class DownloadsView(generic.TemplateView):
	template_name = 'blog/downloads.html'

class ContactView(generic.TemplateView):
	template_name = 'blog/contact.html'

class ContribView(generic.TemplateView):
	template_name = 'blog/contributors.html'

def post(request):
	"""Handles new blog posts"""
	ImageFormSet = modelformset_factory(PostImage, form=ImageForm, extra=1)

	if request.method == 'POST':
		postForm = PostForm(request.POST)
		formset = ImageFormSet(request.POST, request.FILES,
							   queryset=PostImage.objects.none())
		
		if postForm.is_valid() and formset.is_valid():
			post_form = postForm.save(commit=False)
			#TODO: Change when users are implemented
			post_form.user = 'Admin'
			post_form.save()

			for form in formset.cleaned_data:
				if form:
					image = form['image']
					post_picture = PostImage(post=post_form, image=post_picture)
			messages.success(request, "Post successfully added")
			return HttpResponseRedirect('/')
	else:
		postForm = PostForm()
		formset = ImageFormSet(queryset=PostImage.objects.none())
	return render(request, 
					'blog/post.html', 
					{'postForm': postForm, 'formset': formset})

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
    <div id="content" class="single">
        <div class="post">
            <h3>What? Who? Why?</h3>
            <div class="text">
                <p><img src="{% static 'images/about-image.jpg' %}"/></p>
                <p>To all educational institutions, students are not assets, not capital.&nbsp;Students have the capacity to think and to voice out opinions independently without affiliation to any political parties and councils. &nbsp;</p>
                <p>Initiated by several like-minded students from The University of Nottingham Malaysia Campus (UNMC) in 2011, <em>Students in Resistance</em> has since widened its outreach and has been receiving contributions from undergraduates, postgraduates, as well as writers from and beyond UNMC. &nbsp;&nbsp;</p>
                <p><em>Students in Resistance</em> is not just a group. It is a radical platform, a laboratory &ndash; experimental and organic. Contributions from students are highly encouraged.&nbsp;Writers may come and go.&nbsp;The aim is to ignite sparks, to trigger debates.&nbsp;</p>
                <p>Our zines are usually distributed for free in selected universities in Malaysia. Each zine can also be downloaded online in PDF format. This initiative is entirely funded and managed by students with occasional donation from the public.</p>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:500|Oswald:600|Spectral:500" rel="stylesheet" type="text/css">
        <title>Students In Resistance</title>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script>
        <script src="https://static.tumblr.com/thpaaos/lLwkowcqm/jquery.masonry.js"></script>
	    <script>$(window).load(function () { $('.masonary').masonry(); }); </script>
    </head>
    <body>
        <div id="container">
            <div id="header">
                <div id="login">
                    {% if user.is_authenticated %}
                        <a href="{% url 'accounts:logout' %}">logout</a>
                    {% else %}
                        <a href="{% url 'accounts:login' %}">login/register</a>
                    {% endif %}
                </div>
                <h1><a href="{% url 'blog:index' %}"><img src="{% static 'images/header-image.jpg' %}"/></a></h1>
				<h2 style="margin-top:15px; font-size:1.4em">
					<a href="{% url 'blog:about' %}">ABOUT</a>&nbsp;&nbsp;<a href="{% url 'blog:downloads' %}">               DOWNLOADS</a>&nbsp;&nbsp;<a href="{% url 'blog:contributors' %}">           CONTRIBUTORS</a>&nbsp;&nbsp;<a href="{% url 'blog:team' %}">          TEAM</a>&nbsp;&nbsp;<a href="{% url 'blog:contact' %}">           CONTACT</a>&nbsp;&nbsp;
				</h2>
            </div>
            {% block content %}
            {% endblock %}
            <div id="footer">
                <div class="footer-center"><a href="/blog">Subscribe via RSS</a>. Designed by <a href="http://www.sleepoversf.com/">Sleepover</a>.</div>
            </div>
        </div>
    </body>
</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
    <div id="content" class="single">
        <div class="post">
            <h3>Do you have something to say?</h3>
            <div class="text">
                <p><img src="{% static 'images/pen-your-thought.jpg' %}"/></p>
                <p>Interested to contribute? This platform accepts a wide variety of texts, from creative to academic writings, from experimental non-fictions to word plays.&nbsp;Usually, the editorial team will propose a theme. For this reason, it is advisable to contact us so that we can keep you in the loop prior to submission: <strong>studentsinresistance@gmail.com</strong></p>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% block content %}
    <div id="content" class="single">
        <div class="post">
            <h3>{{ post.title }}</h3>
            <div class="text">
                <p><i>By {{ post.author }}</i></p>
                <p>{{ post.text }}</p>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/downloads.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
    <div id="content" class="single">
        <div class="post">
            <h3>Download Our Free Zines</h3>
            <div class="text">
                <p><img src="{% static 'images/download-image.jpg' %}"></p>
                <p><strong>#0/10:</strong> <a href="https://t.umblr.com/redirect?z=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D0B0qfyaWUV7k5c2UwZEhZWGZZX0k&amp;t=NzhjYzhhMzE4NjNkY2MwOTA3NTUwNDgxYWUyNWNjODBiNzY0ZDg5MyxUbU4zdWpESg%3D%3D&amp;p=&amp;m=0" target="_blank">Some Notes For 2012 [Concerning Education]</a>, <em>launch issue</em>&nbsp;</p>
                <p><strong>#1/10:</strong> <a href="https://t.umblr.com/redirect?z=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D0B0qfyaWUV7k5MjdwSVVDOE5Kc0k&amp;t=NmMwNGY0YTExNWM1MmY3MGMzYjVhMjlhODc5MTQ2MjNhNzg3ODc4NCxUbU4zdWpESg%3D%3D&amp;p=&amp;m=0" target="_blank">Hey, You There! [Interpreting Media]</a></p>
                <p><strong>#2/10:</strong>&nbsp;<a href="https://t.umblr.com/redirect?z=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D0B0qfyaWUV7k5TmtPUVNvU01Yb2c&amp;t=YTU1OGNjYzA1NmIzODhkZDc1NWY0NmFjZjE0N2E0YWUxMTczOGQwZCxUbU4zdWpESg%3D%3D&amp;p=&amp;m=0" target="_blank">OMG [Religion, Faith &amp; Belief]</a></p>
                <p><strong>#3/10:</strong> <a href="https://t.umblr.com/redirect?z=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D0B0qfyaWUV7k5cVluTHk4clFoY0k&amp;t=NTAxYzNmMzZhM2IyNmVlZDMzOWYwZTJkODIzMzI3MmQ4MjJlYzIxMixUbU4zdWpESg%3D%3D&amp;p=&amp;m=0" target="_blank">Revolution [Politics of Culture]</a></p>
                <p><strong>#4/10:</strong>&nbsp;<a href="https://t.umblr.com/redirect?z=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D0B0qfyaWUV7k5dTlRVldrTjdtVk0&amp;t=MzAyYzljZTVmMzIwZjM1Yzc3ODNjZDhlYjkwMjIwNDhjYWFhZThkZCxUbU4zdWpESg%3D%3D&amp;p=&amp;m=0" target="_blank">Whoosh&hellip;Thud&hellip;Splaaash&hellip;Chwop&hellip;Thump&hellip;Vrroooooooomm&hellip;Thwuuuk [Sports]</a></p>
                <p><strong>#5/10:</strong>&nbsp;<a href="https://t.umblr.com/redirect?z=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D0B0qfyaWUV7k5YTNwcTFlemVSa2M&amp;t=MTk1ZDdmMzAxNmZkMzE5ODBkYjQwMjg2YmQyZjE5ZGJlY2I0NzdiZCxUbU4zdWpESg%3D%3D&amp;p=&amp;m=0" target="_blank">Global My Ass. [Globalisation]</a></p>
                <p><strong>#6/10:</strong> <a href="https://t.umblr.com/redirect?z=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D0B0qfyaWUV7k5LTNEQU9Pa3NPb0U&amp;t=MTliYjZhYWY4YmRjZTNiOTk5NDBjZDc1MzUzNzY4YzQxYjI1ZmFjYSxUbU4zdWpESg%3D%3D&amp;p=&amp;m=0" target="_blank">Not Dead Yet. [Death]</a></p>
                <p><strong>#7/10: </strong><a href="https://t.umblr.com/redirect?z=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D0B0qfyaWUV7k5SU1LVUFmXzgzU3c&amp;t=ZTEyMTAzZWI4YjY1Y2U5MWVmOTU3MjUwMTZmNWI2Nzc5NzA4ZWE2NyxUbU4zdWpESg%3D%3D&amp;p=&amp;m=0" target="_blank">So one day, some very important people wrote down my rights onto sheets of paper that are now behind glass&hellip; [Yeah &lsquo;Right&rsquo;]</a></p>
                <p><strong>#8/10:</strong> <a href="https://t.umblr.com/redirect?z=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D0B0qfyaWUV7k5ak1yQWhZaE15a2c&amp;t=NWU3OGEyNDk1ODg5YTFkY2RlMDVmYTRkMjNlYjJmMzM5YTQwMTA5NCxUbU4zdWpESg%3D%3D&amp;p=&amp;m=0" target="_blank">Erection [Election Afterthought]</a></p>
                <p><strong>#9/10:</strong> <a href="https://t.umblr.com/redirect?z=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D0B0qfyaWUV7k5SGFTTHNGaTByTVk&amp;t=NjRhYWZmNjY3YmMzYTRhNTI0OTIxNzlkZTZiZjliMDczMjg2N2QyNCxUbU4zdWpESg%3D%3D&amp;p=&amp;m=0" target="_blank">Quick to Spark, Slow to Flame [Resistance]</a></p>
                <p><strong>#10/10:</strong> <a href="https://t.umblr.com/redirect?z=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D0B0qfyaWUV7k5WktzWF9ZN0RRNms&amp;t=OTgxZjdlMjQ4ZTJkYmQ1ODMyZmIxMGM0NTM0YTdlNTJiMzkxMjkxMCxUbU4zdWpESg%3D%3D&amp;p=&amp;m=0" target="_blank">Mind F*** [Mental Colonisation]</a></p>
                <p><strong>#11: </strong><a href="https://t.umblr.com/redirect?z=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D0B0qfyaWUV7k5b0pXdl9JcThyb3c&amp;t=ZTVlM2JkNTg3MzYyY2IzYWVmMDMzM2Q5ZTM1NzBhZTM0MTk5NDU3ZCxUbU4zdWpESg%3D%3D&amp;p=&amp;m=0" target="_blank">Malaysia&nbsp;&iquest;Boleh? [Hope &amp; Disappointment]</a></p>
                <p><strong>#12:</strong> <a href="https://t.umblr.com/redirect?z=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D0B0qfyaWUV7k5eHRsQkh2d1JKaEU&amp;t=YjBjZjgxYzVlOGM4Y2JiZTM2ZGIxMzFiZTk4MTlhYmM5N2NhZTg3YyxUbU4zdWpESg%3D%3D&amp;p=&amp;m=0" target="_blank">No One Leaves Home Unless Home Is the Mouth of a Shark [Home | Rumah]</a></p>
            </div>
        </div>

    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block content %}
    {% if latest_posts %}
    <div id="content">
        <div class="masonary">
        <div class="post">
        {% for post in latest_posts %}
            <h3><a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></h3>
            <div class="post-meta"><p>Published: {{ post.published_date }}</p></div>
            <div class="text"><p>{{ post.text|truncatewords:50 }}</p></div>
        {% endfor %}
        </div>
        </div>
    </div>
    {% else %}
        <p>No blog posts are available.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/post.html
{% extends 'blog/base.html' %}
{% block content %}
    <form id="post_form" method="post" action="" enctype="multipart/form-data">

        {% csrf_token %}
        {% for hidden in postForm.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in postForm %}
            {{ field }} <br />
        {% endfor %}

        {{ formset.management_form }}
        {% for form in formset %}
            {{ form }}
        {% endfor %}


        <input type="submit" name="submit" value="Submit" />
    </form>
{% endblock %}

blog/templates/blog/team.html
{% extends 'blog/base.html' %}
{% block content %}
    <div id="content" class="single">
        <div class="post">
            <h3>Team</h3>
            <div class="text">
            <p><strong>TAN ZI HAO&nbsp;</strong>(editor, illustrator) is a multi-disciplinary conceptual artist, writer, graphic designer, and researcher. He founded <em>Students in Resistance </em>with an ambition to advocate intellectual activism in Malaysia. Through this platform he encourages students to write and critique. His broader academic and artistic interests include the politics of language, Southeast Asian history, art criticism, and anarchism.</p>
            <p><strong>YVONNE TAN YIT FONG&nbsp;</strong>(editor, writer) is an English literature student on a quest for the narratives in Malaysia. The Chinese secret societies, the legends of princesses, and our everyday epics are just some of them. She is also a sucker for postcolonialism.</p>
            </div>
        </div>
    </div>
{% endblock %}